# Generated by Django 5.2.8 on 2025-12-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('photo_url', models.URLField()),
                ('avail_location',models.CharField(max_length=50)),
            ],
        ),
    ]
